name: Deploy Python Scripts

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        # python hello.py 

    - name: Deploy to server
      run: |
        # Replace with your deployment script or commands
        
        #scp -r your_python_scripts/ user@your_server_ip:/path/to/destination/

        
